---
name: LinkNet ResNest50d - Full HD
description: Train LinkNet on RxImage_Segment dataset
labels:
    - LinkNet
    - ResNest50d
    - Full HD
    - Focal Tversky and MS-SSIM loss
max_restarts: 0
records_per_epoch: 52000
scheduling_unit: 100
min_validation_period:
    epochs: 1

checkpoint_storage:
    host_path: /mnt/share/RxConnect/checkpoints
    storage_path: semantic_segmentation
    type: shared_fs

data:
    url: https://drive.google.com/file/d/1wSYUemDsk0CrE49ST_I2zsHca83uLgjr/view?usp=sharing
    md5: 910d97ce43688f5b75d9ab6ca6408d9e
    download_dir: /mnt/share/RxConnect
    force_download: false
    filename: RxImage_Segment.zip
    num_workers: 6
    image_size:
        - 1080
        - 1920

environment:
    image:
        gpu: determinedai/environments:cuda-11.8-pytorch-2.0-gpu-mpi-0.24.0

hyperparameters:
    smp_config:
        model: LinkNet
        encoder: timm-resnest50d
        encoder_weights: imagenet

    global_batch_size: 6
    patience: 10
    lr_config:
        lr_T_max: 10
        lr_eta_min: 1e-6
        lr_last_epoch: -1
    optimizer_config:
        optimizer: AdamW
        weight_decay: 1e-4
        gradient_clip_val: 0.5

    # Loss Coefficients
    loss:
        focal_tversky_loss:
            coef: 1.0
            alpha: 0.35 # Higher alpha -> More weight to false negatives (0, 1)
            beta: 0.75 # Higher beta -> More weight to false positives (0, 1)
            gamma: 2 # Higher gamma -> More weight to hard examples (0, inf)
        ms_ssim_loss:
            coef: 1.0

profiling:
    begin_on_batch: 0
    enabled: true
    end_after_batch:
    sync_timings: true

searcher:
    name: single
    metric: dataset_iou
    smaller_is_better: false
    max_length:
        epochs: 100

debug: false
entrypoint: rx_connect.segmentation.semantic.model_def:SegTrial
workspace: workspace2
project: Semantic_Segmentation
resources:
    resource_pool: workspace1
    slots_per_trial: 1
    shm_size: 17179869184
