---
name: semantic_seg_const
description: Train DeepLabV3+ on RxImage dataset
labels:
    - Semantic_Segmentation
max_restarts: 0
records_per_epoch: 20000
scheduling_unit: 100
min_validation_period:
    epochs: 1

checkpoint_storage:
    host_path: /mnt/share/RxConnect/checkpoints
    storage_path: semantic_segmentation
    type: shared_fs

data:
    url: https://drive.google.com/file/d/1sVXW1UirpDvzMANyV9M4zaIqaia2X-Mo/view?usp=sharing
    md5: c931b863f1aec03030831562a2d44547
    download_dir: /mnt/share/RxConnect
    force_download: false
    filename: RxImage_Segment.zip
    num_workers: 6
    image_size:
        - 720
        - 1280

hyperparameters:
    encoder: resnet18
    global_batch_size: 64
    patience: 10
    initial_lr: 1e-4
    lr_config:
        lr_T_max: 10
        lr_eta_min: 1e-6
        lr_last_epoch: -1
    optimizer_config:
        optimizer: AdamW
        weight_decay: 1e-4
        gradient_clip_val: 0.5

    # Loss Coefficients
    loss:
        lovasz_loss:
            coef: 0.25
            per_image: false
        focal_loss:
            coef: 1.5
            alpha: 0.75
            gamma: 5

profiling:
    begin_on_batch: 0
    enabled: true
    end_after_batch:
    sync_timings: true

searcher:
    name: single
    metric: dataset_iou
    smaller_is_better: false
    max_length:
        epochs: 50

debug: false
entrypoint: rx_connect.segmentation.semantic.model_def:SegTrial
workspace: workspace2
project: Semantic_Segmentation
resources:
    resource_pool: workspace1
    slots_per_trial: 1
