---
name: semantic_seg_const
description: Segmentation Experiment
labels:
    - Semantic_Segmentation
max_restarts: 0
records_per_epoch: 20
scheduling_unit: 500
min_validation_period:
    epochs: 1

bind_mounts:
    - host_path: /Users/dvsingxe/ai-lab-RxConnect/data
      container_path: /Users/dvsingxe/ai-lab-RxConnect/data
      read_only: false

data:
    url: https://drive.google.com/file/d/1sVXW1UirpDvzMANyV9M4zaIqaia2X-Mo/view?usp=sharing
    md5: c931b863f1aec03030831562a2d44547
    download_dir: /Users/dvsingxe/ai-lab-RxConnect/data
    force_download: false
    filename: RxImage_Segment.zip
    num_workers: 0
    image_size:
        - 416
        - 720

hyperparameters:
    encoder: resnet18
    global_batch_size: 4
    patience: 1
    initial_lr: 0.001
    lr_T_max: 2
    lr_eta_min: 0
    lr_last_epoch: -1
    optimizer: AdamW
    weight_decay: 0.0001
    gradient_clip_val: 0.1

    # Loss Coefficients
    loss:
        lovasz_loss:
            coef: 0.1
            per_image: true
        focal_loss:
            coef: 0.9
            alpha: 0.5
            gamma: 2

searcher:
    name: single
    metric: dataset_iou
    smaller_is_better: false
    max_length:
        epochs: 100

entrypoint: rx_connect.segmentation.semantic.model_def:SegTrial
