---
name: semantic_seg_const
description: Segmentation Experiment
labels:
    - Semantic_Segmentation
max_restarts: 0
records_per_epoch: 20000
scheduling_unit: 500
min_validation_period:
    epochs: 1

bind_mounts:
    - host_path: /Users/dvsingxe/ai-lab-RxConnect/data
      container_path: /Users/dvsingxe/ai-lab-RxConnect/data
      read_only: false

data:
    url: https://drive.google.com/file/d/1sVXW1UirpDvzMANyV9M4zaIqaia2X-Mo/view?usp=sharing
    md5: c931b863f1aec03030831562a2d44547
    download_dir: /Users/dvsingxe/ai-lab-RxConnect/data
    force_download: false
    filename: RxImage_Segment.zip
    num_workers: 0
    image_size:
        - 416
        - 720

hyperparameters:
    encoder: resnet18
    global_batch_size: 4
    monitor: val_loss
    patience: 0
    initial_lr: 0.001
    lr_patience: 2
    lr_factor: 0.1
    optimizer: AdamW
    weight_decay: 0.0001

searcher:
    name: single
    metric: val_loss
    max_length:
        epochs: 100
    smaller_is_better: true

entrypoint: rx_connect.segmentation.semantic.model_def:SegTrial
