---
semantic_segmentation:
    model: DeepLabV3Plus
    arch: resnet50
    model_path: /media/RxConnectShared/checkpoints/segmentation/semantics/${.model}/best_${.arch}.pt
    image_size:
        - 720
        - 1280
