---
semantic_segmentation:
    model: Linknet
    arch: timm-efficientnet-b4
    model_path: /media/RxConnectShared/checkpoints/segmentation/semantics/${.model}/best_linknet-${.arch}.pt
    image_size:
        - 1080
        - 1920
